# frozen_string_literal: true

module Redesign
  # The preset marks a group's currency can wear ("Ikona waluty").
  #
  # 24x24 and `currentColor`, like the glyphs, because one file has to read
  # correctly on the cream token face (`.gh-tok`, `.gh-pz--cur`) in both themes.
  # Inlined by RedesignHelper#gh_currency_icon for that reason.
  #
  # Generated by design/mockup-src/tools/extract_group_art.mjs from the wizard's
  # CV map plus `bit`, which only the settings screen offers (30-isg.js:56).
  #
  # Note these are NOT the 64px glyphs of the same name: Glyphs' `carrot` is a
  # different drawing at a different size, and swapping one for the other makes
  # a coin that does not fit its rim.
  class CurrencyIcons < PresetSet
    # Picker order: the wizard's four (30-form.js:15-18), then `bit`.
    KEYS = %w[carrot coin gem pearl bit].freeze

    # The wizard's CVN map, plus a name for `bit` — the mockup's CUR table
    # declines it as "Bit / Bity / Bitów" (00-shared.js:97).
    LABELS = {
      'bit'    => 'Bit',
      'carrot' => 'Marchewka',
      'coin'   => 'Moneta',
      'gem'    => 'Klejnot',
      'pearl'  => 'Perła',
    }.freeze

    class << self
      def dir = 'redesign/currency'
      def labels = LABELS
    end
  end
end
