service: gamification_hub
image: cub8/gamification_hub

ssh:
  user: gamification-hub
  keys:
    - ~/.ssh/id_gamification_hub

servers:
  web:
    hosts:
      - 150.254.78.144
    boot:
      limit: 1
  job:
    hosts:
      - 150.254.78.144
    cmd: bin/jobs

registry:
  username: cub8
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - GAMIFICATION_HUB_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: false

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "/opt/gamification-hub/storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
